# Generated by Django 5.1.5 on 2025-02-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('-id',), 'verbose_name': 'Элемент ToDo', 'verbose_name_plural': 'Элементы ToDo'},
        ),
    ]
